services:
  benchmark-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benchmark-runner
    volumes:
      - ./src:/benchmark/src:ro
      - ./pom.xml:/benchmark/pom.xml:ro
      - ./scripts:/benchmark/scripts:ro
      - ./benchmark-results:/benchmark/benchmark-results
      - ~/.m2/repository:/root/.m2/repository:ro
      - ./docker/test-classes:/benchmark/target/test-classes
    tty: true
    stdin_open: true
    entrypoint:
        - /bin/bash
        - -c
        - "cd /benchmark/scripts && ./run-docker-benchmarks.sh"
    mem_limit: 48g
    mem_reservation: 48g
    cpu_count: 1
    cpus: 1
    cpuset: "0"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio:
        soft: 99
        hard: 99
    depends_on:
        benchmark-db:
          condition: service_healthy

  benchmark-db:
    image: postgres:17.4-alpine3.21
    container_name: benchmark-db
    environment:
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark
      POSTGRES_DB: benchmark
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U benchmark -d benchmark -h localhost'" ]
      interval: 2s
      timeout: 30s
      retries: 10
      start_period: 2s
