services:
  benchmark-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benchmark-runner
    volumes:
      - ./src:/benchmark/src:ro
      - ./pom.xml:/benchmark/pom.xml:ro
      - ./scripts:/benchmark/scripts:ro
      - ./benchmark-results:/benchmark/benchmark-results
      - ~/.m2/repository:/root/.m2/repository:ro
    tty: true
    stdin_open: true
    entrypoint:
        - /bin/bash
        - -c
        - "cd /benchmark/scripts && ./run-benchmarks.sh"
    mem_limit: 6g
    cpus: 2
