jmhConfig:
  warmupIterations: 20
  warmupTime: 1000
  measurementIterations: 10
  measurementTime: 1000
jvmConfig:
  options:
  - -Xms32g
  - -Xmx32g
  - -XX:+UseZGC
  - -XX:+AlwaysPreTouch
runConfig:
  optimizeOnly: true
  scenarios:
  - Create
  - Read
  - Update
  - Delete
  versionings:
  - Novers
  - Javers
  - Envers
  payloadTypes:
  - Basic
  - Extended
  objectGraphComplexities:
  - Single
  - Medium
  - High
benchmark:
  create:
    novers:
      single:
        objects:
          basic: 900000
          basicOptimized: true
          extended: 900000
          extendedOptimized: true
      medium:
        objects:
          basic: 300000
          basicOptimized: true
          extended: 256816
          extendedOptimized: false
      high:
        objects:
          basic: 38791
          basicOptimized: true
          extended: 35095
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 300000
          basicOptimized: false
          extended: 300000
          extendedOptimized: false
      medium:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
      high:
        objects:
          basic: 50000
          basicOptimized: false
          extended: 50000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 163831
          basicOptimized: true
          extended: 74490
          extendedOptimized: true
      medium:
        objects:
          basic: 47856
          basicOptimized: true
          extended: 18572
          extendedOptimized: true
      high:
        objects:
          basic: 6766
          basicOptimized: true
          extended: 2431
          extendedOptimized: true
  read:
    novers:
      single:
        objects:
          basic: 1961011
          basicOptimized: true
          extended: 1800000
          extendedOptimized: true
      medium:
        objects:
          basic: 1116964
          basicOptimized: true
          extended: 787725
          extendedOptimized: true
      high:
        objects:
          basic: 200000
          basicOptimized: true
          extended: 134107
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 1000000
          basicOptimized: false
          extended: 800000
          extendedOptimized: false
      medium:
        objects:
          basic: 600000
          basicOptimized: false
          extended: 600000
          extendedOptimized: false
      high:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 1874236
          basicOptimized: false
          extended: 1208775
          extendedOptimized: false
      medium:
        objects:
          basic: 864553
          basicOptimized: false
          extended: 600000
          extendedOptimized: false
      high:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
  update:
    novers:
      single:
        objects:
          basic: 600000
          basicOptimized: true
          extended: 600000
          extendedOptimized: true
      medium:
        objects:
          basic: 177272
          basicOptimized: true
          extended: 182344
          extendedOptimized: true
      high:
        objects:
          basic: 27172
          basicOptimized: true
          extended: 24736
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 600000
          basicOptimized: false
          extended: 600000
          extendedOptimized: false
      medium:
        objects:
          basic: 400000
          basicOptimized: false
          extended: 400000
          extendedOptimized: false
      high:
        objects:
          basic: 100000
          basicOptimized: false
          extended: 100000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 400000
          basicOptimized: false
          extended: 400000
          extendedOptimized: false
      medium:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
      high:
        objects:
          basic: 50000
          basicOptimized: false
          extended: 50000
          extendedOptimized: false
  delete:
    novers:
      single:
        objects:
          basic: 639974
          basicOptimized: true
          extended: 600000
          extendedOptimized: true
      medium:
        objects:
          basic: 223544
          basicOptimized: true
          extended: 220299
          extendedOptimized: true
      high:
        objects:
          basic: 38085
          basicOptimized: true
          extended: 33508
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 600000
          basicOptimized: false
          extended: 600000
          extendedOptimized: false
      medium:
        objects:
          basic: 400000
          basicOptimized: false
          extended: 400000
          extendedOptimized: false
      high:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
      medium:
        objects:
          basic: 200000
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
      high:
        objects:
          basic: 50000
          basicOptimized: false
          extended: 50000
          extendedOptimized: false
