spring:
  application:
    name: bth-thesis-javers-hibernateenvers
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/benchmark
    username: benchmark
    password: benchmark

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org:
      javers: WARN
      hibernate:
        orm:
          deprecation: ERROR
    root: WARN

thesis:
  payload:
    size: 200
