jmhConfig:
  warmupIterations: 20
  warmupTime: 1000
  measurementIterations: 10
  measurementTime: 1000
jvmConfig:
  options:
  - -Xms32g
  - -Xmx32g
  - -XX:+UseZGC
  - -XX:+AlwaysPreTouch
runConfig:
  optimizeOnly: true
  scenarios:
  - Create
  - Read
  - Update
  - Delete
  versionings:
  - Novers
  - Javers
  - Envers
  payloadTypes:
  - Basic
  - Extended
  objectGraphComplexities:
  - Single
  - Medium
  - High
benchmark:
  create:
    novers:
      single:
        objects:
          basic: 665941
          basicOptimized: false
          extended: 669735
          extendedOptimized: false
      medium:
        objects:
          basic: 234730
          basicOptimized: false
          extended: 214570
          extendedOptimized: false
      high:
        objects:
          basic: 31747
          basicOptimized: false
          extended: 29997
          extendedOptimized: false
    envers:
      single:
        objects:
          basic: 174838
          basicOptimized: false
          extended: 207013
          extendedOptimized: false
      medium:
        objects:
          basic: 65674
          basicOptimized: false
          extended: 61710
          extendedOptimized: false
      high:
        objects:
          basic: 8857
          basicOptimized: false
          extended: 8797
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 122404
          basicOptimized: false
          extended: 56850
          extendedOptimized: false
      medium:
        objects:
          basic: 26680
          basicOptimized: false
          extended: 10558
          extendedOptimized: false
      high:
        objects:
          basic: 4783
          basicOptimized: false
          extended: 1494
          extendedOptimized: false
  read:
    novers:
      single:
        objects:
          basic: 1897782
          basicOptimized: false
          extended: 1416640
          extendedOptimized: false
      medium:
        objects:
          basic: 1027858
          basicOptimized: false
          extended: 788118
          extendedOptimized: false
      high:
        objects:
          basic: 184560
          basicOptimized: false
          extended: 123196
          extendedOptimized: false
    envers:
      single:
        objects:
          basic: 1070457
          basicOptimized: false
          extended: 606019
          extendedOptimized: false
      medium:
        objects:
          basic: 392672
          basicOptimized: false
          extended: 283112
          extendedOptimized: false
      high:
        objects:
          basic: 78540
          basicOptimized: false
          extended: 50876
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 976816
          basicOptimized: false
          extended: 1101309
          extendedOptimized: false
      medium:
        objects:
          basic: 815017
          basicOptimized: false
          extended: 506250
          extendedOptimized: false
      high:
        objects:
          basic: 151875
          basicOptimized: false
          extended: 67500
          extendedOptimized: false
  update:
    novers:
      single:
        objects:
          basic: 480345
          basicOptimized: false
          extended: 442639
          extendedOptimized: false
      medium:
        objects:
          basic: 158032
          basicOptimized: false
          extended: 153792
          extendedOptimized: false
      high:
        objects:
          basic: 25357
          basicOptimized: false
          extended: 20853
          extendedOptimized: false
    envers:
      single:
        objects:
          basic: 157016
          basicOptimized: false
          extended: 151201
          extendedOptimized: false
      medium:
        objects:
          basic: 58196
          basicOptimized: false
          extended: 53452
          extendedOptimized: false
      high:
        objects:
          basic: 9193
          basicOptimized: false
          extended: 8370
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 56137
          basicOptimized: false
          extended: 19743
          extendedOptimized: false
      medium:
        objects:
          basic: 14284
          basicOptimized: false
          extended: 6012
          extendedOptimized: false
      high:
        objects:
          basic: 2116
          basicOptimized: false
          extended: 877
          extendedOptimized: false
  delete:
    novers:
      single:
        objects:
          basic: 553108
          basicOptimized: false
          extended: 497997
          extendedOptimized: false
      medium:
        objects:
          basic: 204601
          basicOptimized: false
          extended: 173799
          extendedOptimized: false
      high:
        objects:
          basic: 34569
          basicOptimized: false
          extended: 30375
          extendedOptimized: false
    envers:
      single:
        objects:
          basic: 85426
          basicOptimized: false
          extended: 88089
          extendedOptimized: false
      medium:
        objects:
          basic: 38287
          basicOptimized: false
          extended: 33708
          extendedOptimized: false
      high:
        objects:
          basic: 6938
          basicOptimized: false
          extended: 6187
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 40879
          basicOptimized: false
          extended: 36771
          extendedOptimized: false
      medium:
        objects:
          basic: 32860
          basicOptimized: false
          extended: 30804
          extendedOptimized: false
      high:
        objects:
          basic: 12457
          basicOptimized: false
          extended: 11943
          extendedOptimized: false
