jmhConfig:
  warmupIterations: 20
  warmupTime: 1000
  measurementIterations: 10
  measurementTime: 1000
jvmConfig:
  options:
  - -Xms32g
  - -Xmx32g
  - -XX:+UseZGC
  - -XX:+AlwaysPreTouch
runConfig:
  optimizeOnly: true
  scenarios:
  - Create
  - Read
  - Update
  - Delete
  versionings:
  - Novers
  - Javers
  - Envers
  payloadTypes:
  - Basic
  - Extended
  objectGraphComplexities:
  - Single
  - Medium
  - High
benchmark:
  create:
    novers:
      single:
        objects:
          basic: 900000
          basicOptimized: true
          extended: 900000
          extendedOptimized: true
      medium:
        objects:
          basic: 300000
          basicOptimized: true
          extended: 256816
          extendedOptimized: true
      high:
        objects:
          basic: 38791
          basicOptimized: true
          extended: 35095
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 450000
          basicOptimized: false
          extended: 450000
          extendedOptimized: false
      medium:
        objects:
          basic: 111806
          basicOptimized: false
          extended: 112994
          extendedOptimized: false
      high:
        objects:
          basic: 16045
          basicOptimized: false
          extended: 15470
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 163831
          basicOptimized: true
          extended: 74490
          extendedOptimized: true
      medium:
        objects:
          basic: 47856
          basicOptimized: true
          extended: 18572
          extendedOptimized: true
      high:
        objects:
          basic: 6766
          basicOptimized: true
          extended: 2431
          extendedOptimized: true
  read:
    novers:
      single:
        objects:
          basic: 1961011
          basicOptimized: true
          extended: 1800000
          extendedOptimized: true
      medium:
        objects:
          basic: 1116964
          basicOptimized: true
          extended: 787725
          extendedOptimized: true
      high:
        objects:
          basic: 200000
          basicOptimized: true
          extended: 134107
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 1500000
          basicOptimized: false
          extended: 1200000
          extendedOptimized: false
      medium:
        objects:
          basic: 900000
          basicOptimized: false
          extended: 900000
          extendedOptimized: false
      high:
        objects:
          basic: 200000
          basicOptimized: true
          extended: 200000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 1874236
          basicOptimized: true
          extended: 786447
          extendedOptimized: false
      medium:
        objects:
          basic: 1220832
          basicOptimized: false
          extended: 675000
          extendedOptimized: false
      high:
        objects:
          basic: 150000
          basicOptimized: false
          extended: 75000
          extendedOptimized: false
  update:
    novers:
      single:
        objects:
          basic: 600000
          basicOptimized: true
          extended: 600000
          extendedOptimized: true
      medium:
        objects:
          basic: 177272
          basicOptimized: true
          extended: 182344
          extendedOptimized: true
      high:
        objects:
          basic: 27172
          basicOptimized: true
          extended: 24736
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 391909
          basicOptimized: false
          extended: 385166
          extendedOptimized: false
      medium:
        objects:
          basic: 153628
          basicOptimized: false
          extended: 138994
          extendedOptimized: false
      high:
        objects:
          basic: 23380
          basicOptimized: false
          extended: 20685
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 79814
          basicOptimized: false
          extended: 36248
          extendedOptimized: false
      medium:
        objects:
          basic: 24200
          basicOptimized: false
          extended: 9252
          extendedOptimized: false
      high:
        objects:
          basic: 3489
          basicOptimized: false
          extended: 1328
          extendedOptimized: false
  delete:
    novers:
      single:
        objects:
          basic: 639974
          basicOptimized: true
          extended: 600000
          extendedOptimized: true
      medium:
        objects:
          basic: 223544
          basicOptimized: true
          extended: 220299
          extendedOptimized: true
      high:
        objects:
          basic: 38085
          basicOptimized: true
          extended: 33508
          extendedOptimized: true
    envers:
      single:
        objects:
          basic: 246334
          basicOptimized: false
          extended: 237266
          extendedOptimized: false
      medium:
        objects:
          basic: 95780
          basicOptimized: false
          extended: 89446
          extendedOptimized: false
      high:
        objects:
          basic: 15752
          basicOptimized: false
          extended: 200000
          extendedOptimized: false
    javers:
      single:
        objects:
          basic: 89710
          basicOptimized: false
          extended: 78519
          extendedOptimized: false
      medium:
        objects:
          basic: 60114
          basicOptimized: false
          extended: 51117
          extendedOptimized: false
      high:
        objects:
          basic: 20269
          basicOptimized: false
          extended: 17515
          extendedOptimized: false
